# Generated by Django 2.1.2 on 2018-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=15)),
                ('tamano', models.FloatField()),
                ('peso', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
